name = "supaflare-worker"
main = 'index.js'
usage_model = 'bundled'
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-10-10"
kv_namespaces = [
  { binding = "SUPAFLARE", id = "7fa4f57391474ac8b1306c5d1ba7211e", preview_id = "78c8caceaf6b4228aea01f725ef70527" },
]
